README.md
fetch.js
gatsby-node.js
normalize.js
package.json
src/fetch.js
src/gatsby-node.js
src/normalize.js

Using sync api

---

gatsby-node.js
package.json
src/gatsby-node.js

graphql was giving syntax error while creating node type if content type uid contains "-" character

Hotfix/2.2.5 : replaced - with _ from contentTypeUid 

---

fetch.js
gatsby-node.js
normalize.js
package.json
src/fetch.js
src/gatsby-node.js
src/normalize.js

- attached missing global field schema in content_type schema
- disabled auto schema generation for union type referenced fields

hotfix/2.2.6: added global field schema and disabled auto schema generation referenced fields

---

src/fetch.js

Change `contentstack-gatsby-source-pilugin` to `contentstack-gatsby-source-plugin`

Typo in X-User-Agent

---

gatsby-node.js
src/fetch.js
src/gatsby-node.js
src/normalize.js

Create resolver api

---

normalize.js
package.json
src/normalize.js

Handles null value of group passed.

handle null values passed by groups

---

normalize.js
src/normalize.js

Creates common interface for global fields

common interface for global fields

---

gatsby-node.js
normalize.js
package.json
src/gatsby-node.js
src/normalize.js

File fields inside group fields are not getting resolved on 2.3.0 and above version

File fields not getting resolved

---

gatsby-node.js
src/gatsby-node.js

Creating a PR to add comments to commits

Plugin options schema

---

.babelrc
fetch.js
gatsby-node.js
package.json
src/fetch.js
src/gatsby-node.js
src/utils.js
utils.js

feat: added support for gatsby v4.

---

.babelrc
fetch.js
gatsby-node.js
package.json
src/fetch.js
src/gatsby-node.js
src/utils.js
utils.js

Feat: added support for gatsby v4-alpha.

---

README.md
extend-node-type.js
gatsby-node.js
gatsby-plugin-image.js
package.json
src/extend-node-type.js
src/gatsby-node.js
src/gatsby-plugin-image.js
src/utils.js
utils.js

Updated README.md.
Added user friendly messages for missing dependencies.

refactor: added user friendly error messages for missing dependencies and updated Readme file.

---

contenttype-data.js
create-schema-customization.js
fetch.js
package.json
src/contenttype-data.js
src/create-schema-customization.js
src/fetch.js
src/utils.js
utils.js

1. Caches the content-types downloaded time in ISO format.
2. Changed content-type query building strategy.

feat: optimised build speed by caching content-types downloaded time

---

.babelrc
create-resolvers.js
normalize.js
package.json
src/create-resolvers.js
src/normalize.js

1. Restores foreign key reference for v3 else causes issue when enableSchemaGeneration is false.

hotfix: restored foreign key reference

---

.babelrc
README.md
package.json
src/utils.js
utils.js

Title: Support for azure NA region
Changes: updated the image regex with support of azure stag & azure NA(prod)
Jira ID: https://contentstack.atlassian.net/browse/ECO-893

feat:azure NA support updates ECO-893

---

normalize.js
src/normalize.js

Title: Fix issue for number field
Change: Int type to Float type
Jira: https://contentstack.atlassian.net/browse/ECO-962

fix: Change Int type to Float type ECO-962

---

.github/workflows/codeql-analysis.yml
.github/workflows/sast-scan.yml
.github/workflows/sca-monitor.yml
.github/workflows/sca-scan.yml
.github/workflows/secrets-scan.yml
fetch.js
node-helper.js
src/fetch.js
src/node-helper.js

We investigated a mutual customer that was having trouble with Contentstack and found this issue which @pieh fixed.

fix: support gatsby rendering engines

---

fetch.js
package.json
src/fetch.js

Title: Replace console with reporter activity (From PR: #128 )
Change: added reporter activity to log the status while souring data from Contentstack
JIRA: ECO-1279

Fix/Replace console with reporter ECO-1279

---

README.md
fetch.js
package.json
plugin-options-schema.js
src/fetch.js
src/plugin-options-schema.js

Changes:
- Added HTTP retries for network failures/Timeouts & error_codes beyond 500.
- Added incremental delays on retries
- Updated README for new plugin options i.e. httpRetries

Feat/http retries v4.0.9

---

.github/workflows/npm-publish.yml

Changes
- Added GitHub action to auto-publish on npm.
- On release publish it would trigger the action

feat:added github action to publish on npm

---

package-lock.json
package.json

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1fccUr6MFTq4tf488aivN1nvyY6gk1qQ%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=zMsIoad)
Changes: 
- upgraded source filesystem plugin for snyk fix
- tested dev side

fix:[ECO-2487] Snyk fixes

---

README.md
fetch.js
package.json
plugin-options-schema.js
src/fetch.js
src/plugin-options-schema.js

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19fzqx0fOcWM9Ul1dsXZsdEfFEkL0Wu6II%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=_XitF4O)
Changes:
- package version bump v5.0.2
- branch support added
- READme update
- npm audit check

feat- [ECO-2571] branch support

---

node-helper.js
package.json
src/node-helper.js

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1hsGXsktKeuG31FKFRaG35Ap19xHbRXo%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=bZbX9II)
Changes:
- stack validation fetch call with branch option
- package version change

fix:ECO-2303 stack validation with branches & package version bump

---

package.json
src/utils.js
utils.js

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1WJ6d8qk8ZyxFg5hxKXmvlv4QooZuws%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=B9qIuKF)
Changes:
- image delivery api azure eu support 
- package version bump

feat:ECO-2736 azure eu support for image delivery api

---

normalize.js
package-lock.json
package.json

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX10wbSO4WOm4WcOBNzjGm2aF0Ue7q92BCE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=ArK5-St)
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1mZxYcKwGiJkm5m01c6G6913QeKCeKm0%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=j4N_Vxf)

version bump

---

package-lock.json
package.json
src/fetch.js

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19dJ1JiVMYIKrJ4GKu7ata7l9sRgTytc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://moontower.gitstream.cm/v2/badge/collaboration-page?magicLinkId=bsUqo11)

Mkt 9075-removed dependency for publish_details key

---

README.md
package-lock.json
package.json

Incorporated Suggested PR: https://github.com/contentstack/gatsby-source-contentstack/pull/151 
to separate out plugin description in table format:

chore: updated readme
